import type { TopNiches } from "@/hooks/useApi";

/** Mirrors src/analytics/top-niches.ts so the Top 10 tab renders without the API. */
export const CURATED_TOP_NICHES: TopNiches = {
  region: "LATAM",
  source: "curated",
  niches: [
    {
      rank: 1,
      name: "Finanzas personales LATAM",
      query: "finanzas personales",
      why: "Alto CPM y búsqueda constante de deudas, ahorro y primer crédito.",
      demand: "alta",
      competition: "alta",
      cpmLongformUsd: 12,
      cpmShortsUsd: 0.08,
      exampleTopics: ["cómo salir de deudas", "tarjeta vs efectivo", "fondo de emergencia"],
      formats: ["short", "long"],
    },
    {
      rank: 2,
      name: "IA práctica (sin jerga)",
      query: "inteligencia artificial",
      why: "Demanda explosiva; gana quien enseña un truco usable en 60s.",
      demand: "alta",
      competition: "alta",
      cpmLongformUsd: 8,
      cpmShortsUsd: 0.06,
      exampleTopics: ["prompt que ahorra 1 hora", "IA para el trabajo", "estafas con IA"],
      formats: ["short"],
    },
    {
      rank: 3,
      name: "Historia en 60 segundos",
      query: "historia",
      why: "Evergreen, fácil de serializar y reutilizar en 4 plataformas.",
      demand: "alta",
      competition: "media",
      cpmLongformUsd: 5,
      cpmShortsUsd: 0.04,
      exampleTopics: ["emperadores", "inventos olvidados", "mitos vs hechos"],
      formats: ["short"],
    },
    {
      rank: 4,
      name: "Recetas rápidas",
      query: "recetas rápidas",
      why: "Retención visual alta; shorts de cocina viajan bien a TikTok y Facebook.",
      demand: "alta",
      competition: "alta",
      cpmLongformUsd: 5,
      cpmShortsUsd: 0.04,
      exampleTopics: ["cena en 15 min", "meal prep barato", "postre 3 ingredientes"],
      formats: ["short"],
    },
    {
      rank: 5,
      name: "Skincare / belleza",
      query: "belleza skincare",
      why: "CPM de belleza alto y marcas dispuestas a canje.",
      demand: "alta",
      competition: "alta",
      cpmLongformUsd: 7,
      cpmShortsUsd: 0.05,
      exampleTopics: ["rutina de noche", "ingrediente vs mito", "piel grasa LATAM"],
      formats: ["short"],
    },
    {
      rank: 6,
      name: "Productividad y estudio",
      query: "productividad estudio",
      why: "Audiencia joven, bajo costo de producción, series fáciles.",
      demand: "media",
      competition: "media",
      cpmLongformUsd: 6,
      cpmShortsUsd: 0.05,
      exampleTopics: ["técnica pomodoro", "apuntes en 1 hoja", "cómo concentrarse"],
      formats: ["short", "long"],
    },
    {
      rank: 7,
      name: "Videojuegos indie",
      query: "videojuegos indie",
      why: "Comunidad fiel; menos saturado que AAA si el recorte es específico.",
      demand: "media",
      competition: "media",
      cpmLongformUsd: 4,
      cpmShortsUsd: 0.03,
      exampleTopics: ["juegos baratos", "hidden gems", "tips de un boss"],
      formats: ["short", "long"],
    },
    {
      rank: 8,
      name: "Salud cotidiana (no médica)",
      query: "salud hábitos",
      why: "Búsqueda diaria de sueño, energía y movimiento; evita consejos clínicos.",
      demand: "alta",
      competition: "media",
      cpmLongformUsd: 5,
      cpmShortsUsd: 0.04,
      exampleTopics: ["dormir mejor", "caminar 8k pasos", "hidratarse"],
      formats: ["short"],
    },
    {
      rank: 9,
      name: "Negocios chicos / side hustle",
      query: "negocios por internet",
      why: "Intención comercial y CPM de finance/education mezclado.",
      demand: "alta",
      competition: "alta",
      cpmLongformUsd: 12,
      cpmShortsUsd: 0.08,
      exampleTopics: ["primera venta", "precios", "errores al emprender"],
      formats: ["short", "long"],
    },
    {
      rank: 10,
      name: "Ciencia curiosa",
      query: "ciencia",
      why: "Alto share; un dato sorprendente por video escala en Shorts.",
      demand: "media",
      competition: "media",
      cpmLongformUsd: 5,
      cpmShortsUsd: 0.04,
      exampleTopics: ["por qué el cielo es azul", "el cerebro en 60s", "espacio"],
      formats: ["short"],
    },
  ],
};
